name: Vectrix Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run All Tests
        run: ./gradlew clean test

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: lib/build/reports/tests/test
